name: Continious Integration

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Node Comment
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
            - name: Run Blague
              run: echo Blague
